language: python
python:
  - "3.6"
install:
  pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "cjjcastro-github" # the key of the org you chose at step #3
    token:
      secure: a3bf3037033797cc9b670eb511bda7f99de61730 # encrypted value of your token
script:
  - echo foo